

export const SampleConst = " Sample Variable for testing ";
export const AllstatesAndCities = {
    "fullName": null,
    "mobileNo": null,
    "businessName": null,
    "emailId": null,
    "picture": null,
    "statesAndCities": {
        "Telangana": {
            "1": "Adilabad",
            "205": "Hanamkonda",
            "221": "Hyderabad City",
            "222": "Hyderabad South East",
            "265": "Karimnagar",
            "274": "Khammam (TL)",
            "314": "Mahabubnagar",
            "334": "Medak",
            "360": "Nalgonda",
            "375": "Nizamabad",
            "396": "Peddapalli",
            "451": "Sangareddy",
            "460": "Secunderabad",
            "497": "Suryapet",
            "552": "Wanaparthy",
            "553": "Warangal"
        },
        "Uttar Pradesh": {
            "2": "Agra",
            "8": "Aligarh",
            "9": "Allahabad",
            "16": "Ambedkar Nagar",
            "28": "Auraiya",
            "31": "Azamgarh",
            "34": "Bagpat",
            "35": "Bahraich",
            "39": "Ballia",
            "40": "Balrampur",
            "42": "Banda",
            "46": "Barabanki",
            "50": "Bareilly",
            "55": "Basti",
            "79": "Bijnor",
            "85": "Budaun",
            "87": "Bulandshahr",
            "98": "Chandauli",
            "114": "Chitrakoot",
            "136": "Deoria",
            "165": "Etah",
            "166": "Etawah",
            "167": "Faizabad",
            "170": "Farrukhabad",
            "172": "Fatehpur",
            "175": "Firozabad",
            "181": "Gautam Buddha Nagar",
            "183": "Ghaziabad",
            "184": "Ghazipur",
            "190": "Gonda",
            "193": "Gorakhpur",
            "204": "Hamirpur (UP)",
            "207": "Hardoi",
            "210": "Hathras",
            "234": "Jalaun",
            "241": "Jaunpur",
            "243": "Jhansi",
            "248": "Jyotiba Phule Nagar",
            "253": "Kannauj",
            "256": "Kanpur Dehat",
            "257": "Kanpur Nagar",
            "271": "Kaushambi",
            "277": "Kheri",
            "297": "Kushinagar",
            "301": "Lalitpur",
            "308": "Lucknow",
            "315": "Maharajganj",
            "317": "Mahoba",
            "318": "Mainpuri",
            "328": "Mathura",
            "329": "Mau",
            "335": "Meerut",
            "338": "Mirzapur",
            "344": "Moradabad",
            "349": "Muzaffarnagar",
            "400": "Pilibhit",
            "409": "Pratapgarh",
            "419": "Raebareli",
            "429": "Rampur",
            "445": "Saharanpur",
            "454": "Sant Kabir Nagar",
            "455": "Sant Ravidas Nagar",
            "465": "Shahjahanpur",
            "468": "Shrawasti",
            "470": "Siddharthnagar",
            "477": "Sitapur",
            "482": "Sonbhadra",
            "493": "Sultanpur",
            "535": "Unnao",
            "544": "Varanasi"
        },
        "Maharashtra": {
            "3": "Ahmed Nagar",
            "7": "Akola",
            "17": "Amravati",
            "29": "Aurangabad",
            "57": "Beed",
            "67": "Bhandara",
            "88": "Buldhana",
            "101": "Chandrapur",
            "146": "Dhule",
            "178": "Gadchiroli",
            "192": "Gondia",
            "214": "Hingoli",
            "235": "Jalgaon",
            "236": "Jalna",
            "284": "Kolhapur",
            "302": "Latur",
            "347": "Mumbai",
            "356": "Nagpur",
            "364": "Nanded",
            "365": "Nandurbar",
            "369": "Nashik",
            "381": "Osmanabad",
            "388": "Parbhani",
            "413": "Pune",
            "422": "Raigarh (MH)",
            "434": "Ratnagiri",
            "452": "Sangli",
            "458": "Satara",
            "472": "Sindhudurg",
            "481": "Solapur",
            "507": "Thane",
            "554": "Wardha",
            "555": "Washim",
            "564": "Yavatmal"
        },
        "Gujarat": {
            "4": "Ahmedabad City",
            "18": "Amreli",
            "21": "Anand",
            "41": "Banasanktha",
            "49": "Bardoli",
            "69": "Bharuch",
            "70": "Bhavnagar",
            "179": "Gandhinagar",
            "191": "Gondal",
            "240": "Jamnagar",
            "247": "Junagadh",
            "276": "Kheda",
            "298": "Kutch",
            "316": "Mahesana",
            "370": "Navsari",
            "386": "Panchmahals",
            "390": "Patan",
            "406": "Porbandar",
            "426": "Rajkot",
            "443": "Sabarkantha",
            "495": "Surat",
            "496": "Surendranagar",
            "540": "Vadodara East",
            "541": "Vadodara West",
            "543": "Valsad"
        },
        "Mizoram": {
            "5": "Aizawl",
            "97": "Champhai",
            "283": "Kolasib",
            "303": "Lawngtlai",
            "310": "Lunglei",
            "320": "Mammit",
            "463": "Serchhip"
        },
        "Rajasthan": {
            "6": "Ajmer",
            "12": "Alwar",
            "45": "Banswara",
            "48": "Baran",
            "51": "Barmer",
            "68": "Bharatpur",
            "71": "Bhilwara",
            "80": "Bikaner",
            "89": "Bundi",
            "116": "Chittorgarh",
            "118": "Churu",
            "132": "Dausa",
            "144": "Dholpur",
            "154": "Dungarpur",
            "180": "Ganganagar",
            "206": "Hanumangarh",
            "231": "Jaipur",
            "232": "Jaisalmer",
            "237": "Jalor",
            "242": "Jhalawar",
            "244": "Jhujhunu",
            "245": "Jodhpur",
            "261": "Karauli",
            "287": "Kota",
            "355": "Nagaur",
            "385": "Pali",
            "427": "Rajsamand",
            "459": "Sawai Madhopur",
            "471": "Sikar",
            "474": "Sirohi",
            "521": "Tonk",
            "528": "Udaipur"
        },
        "Kerala": {
            "10": "Alleppey",
            "13": "Alwaye",
            "92": "Calicut",
            "102": "Changanacherry",
            "163": "Ernakulam",
            "223": "Idukki",
            "228": "Irinjalakuda",
            "255": "Kannur",
            "269": "Kasaragod",
            "288": "Kottayam",
            "325": "Manjeri",
            "330": "Mavelikara",
            "382": "Ottapalam",
            "384": "Palghat",
            "391": "Pathanamthitta",
            "418": "Quilon",
            "506": "Thalassery",
            "518": "Tirur",
            "519": "Tiruvalla",
            "522": "Trichur",
            "523": "Trivandrum North",
            "524": "Trivandrum South",
            "539": "Vadakara"
        },
        "Uttarakhand,Uttaranchal": {
            "11": "Almora",
            "33": "Bageshwar",
            "95": "Chamoli",
            "96": "Champawat",
            "134": "Dehradun",
            "208": "Haridwar",
            "357": "Nainital",
            "395": "Pauri Garhwal",
            "401": "Pithoragarh",
            "441": "Rudraprayag",
            "504": "Tehri Garhwal",
            "529": "Udham Singh Nagar",
            "538": "Uttarkashi"
        },
        "Andhra Pradesh": {
            "14": "Amalapuram",
            "20": "Anakapalle",
            "22": "Anantapur",
            "72": "Bhimavaram",
            "115": "Chittoor",
            "123": "Cuddapah",
            "162": "Eluru",
            "194": "Gudivada",
            "195": "Gudur",
            "198": "Guntur",
            "213": "Hindupur",
            "249": "Kakinada",
            "273": "Khammam (AP)",
            "294": "Kurnool",
            "311": "Machilipatnam",
            "366": "Nandyal",
            "368": "Narasaraopet",
            "373": "Nellore",
            "389": "Parvathipuram",
            "408": "Prakasam",
            "410": "Proddatur",
            "424": "Rajahmundry",
            "490": "Srikakulam",
            "498": "Tadepalligudem",
            "505": "Tenali",
            "515": "Tirupati",
            "547": "Vijayawada",
            "549": "Visakhapatnam",
            "550": "Vizianagaram"
        },
        "Haryana": {
            "15": "Ambala",
            "73": "Bhiwani",
            "168": "Faridabad",
            "200": "Gurugram",
            "215": "Hissar",
            "266": "Karnal",
            "295": "Kurukshetra",
            "438": "Rohtak",
            "483": "Sonepat"
        },
        "Punjab": {
            "19": "Amritsar",
            "52": "Barnala",
            "56": "Bathinda",
            "169": "Faridkot",
            "171": "Fatehgarh Sahib",
            "173": "Fazilka",
            "176": "Firozpur",
            "199": "Gurdaspur",
            "218": "Hoshiarpur",
            "233": "Jalandhar",
            "258": "Kapurthala",
            "309": "Ludhiana",
            "326": "Mansa",
            "339": "Moga",
            "340": "Mohali",
            "346": "Muktsar",
            "372": "Nawanshahr",
            "392": "Patiala",
            "440": "Ropar",
            "442": "Rupnagar",
            "453": "Sangrur",
            "502": "Tarn Taran"
        },
        "Jammu and Kashmir": {
            "23": "Ananthnag",
            "43": "Bandipur",
            "47": "Baramulla",
            "86": "Budgam",
            "153": "Doda",
            "239": "Jammu",
            "263": "Kargil",
            "270": "Kathua",
            "291": "Kulgam",
            "293": "Kupwara",
            "304": "Leh",
            "405": "Poonch",
            "412": "Pulwama",
            "425": "Rajauri",
            "435": "Reasi",
            "491": "Srinagar",
            "530": "Udhampur"
        },
        "Tamil Nadu": {
            "24": "Anna Road H.O",
            "25": "Arakkonam",
            "105": "Chengalpattu",
            "106": "Chennai City Central",
            "107": "Chennai City North",
            "108": "Chennai City South",
            "119": "Coimbatore",
            "122": "Cuddalore",
            "140": "Dharmapuri",
            "151": "Dindigul",
            "164": "Erode",
            "252": "Kanchipuram",
            "254": "Kanniyakumari",
            "260": "Karaikudi",
            "267": "Karur",
            "289": "Kovilpatti",
            "290": "Krishnagiri",
            "292": "Kumbakonam",
            "313": "Madurai",
            "332": "Mayiladuthurai",
            "354": "Nagapattinam",
            "361": "Namakkal",
            "374": "Nilgiris",
            "394": "Pattukottai",
            "403": "Poducherry (TN)",
            "404": "Pollachi",
            "411": "Pudukkottai",
            "428": "Ramanathapuram",
            "447": "Salem East",
            "448": "Salem West",
            "478": "Sivaganga",
            "492": "Srirangam",
            "499": "Tambaram",
            "508": "Thanjavur",
            "509": "Theni",
            "513": "Tiruchirapalli",
            "514": "Tirunelveli",
            "516": "Tirupattur",
            "517": "Tirupur",
            "520": "Tiruvannamalai",
            "527": "Tuticorin",
            "545": "Vellore",
            "548": "Virudhunagar",
            "551": "Vriddhachalam"
        },
        "West Bengal": {
            "26": "Asansol",
            "44": "Bankura",
            "82": "Birbhum",
            "90": "Burdwan",
            "120": "Contai",
            "121": "Cooch Behar",
            "130": "Darjiling",
            "216": "Hooghly",
            "219": "Howrah",
            "238": "Jalpaiguri",
            "285": "Kolkata",
            "319": "Malda",
            "337": "Midnapore",
            "348": "Murshidabad",
            "352": "Nadia",
            "376": "North 24 Parganas",
            "378": "North Dinajpur",
            "416": "Purulia",
            "485": "South 24 Parganas",
            "486": "South Dinajpur",
            "501": "Tamluk"
        },
        "Odisha, Orissa": {
            "27": "Aska",
            "37": "Balangir",
            "38": "Balasore",
            "64": "Berhampur",
            "65": "Bhadrak",
            "76": "Bhubaneswar",
            "124": "Cuttack City",
            "125": "Cuttack North",
            "126": "Cuttack South",
            "143": "Dhenkanal",
            "250": "Kalahandi",
            "272": "Keonjhar",
            "286": "Koraput",
            "333": "Mayurbhanj",
            "399": "Phulbani",
            "414": "Puri",
            "450": "Sambalpur",
            "494": "Sundargarh"
        },
        "Bihar": {
            "30": "Aurangabad(Bihar)",
            "58": "Begusarai",
            "66": "Bhagalpur",
            "74": "Bhojpur",
            "129": "Darbhanga",
            "156": "East Champaran",
            "182": "Gaya",
            "312": "Madhubani",
            "343": "Monghyr",
            "350": "Muzaffarpur",
            "358": "Nalanda",
            "371": "Nawadha",
            "393": "Patna",
            "415": "Purnea",
            "439": "Rohtas",
            "446": "Saharsa",
            "449": "Samastipur",
            "457": "Saran",
            "476": "Sitamarhi",
            "479": "Siwan",
            "542": "Vaishali",
            "556": "West Champaran"
        },
        "Karnataka": {
            "32": "Bagalkot",
            "59": "Belgaum",
            "60": "Bellary",
            "61": "Bengaluru East",
            "62": "Bengaluru South",
            "63": "Bengaluru West",
            "77": "Bidar",
            "78": "Bijapur",
            "104": "Channapatna",
            "111": "Chikmagalur",
            "112": "Chikodi",
            "113": "Chitradurga",
            "141": "Dharwad",
            "177": "Gadag",
            "188": "Gokak",
            "196": "Gulbarga",
            "209": "Hassan",
            "211": "Haveri",
            "268": "Karwar",
            "279": "Kodagu",
            "282": "Kolar",
            "323": "Mandya",
            "324": "Mangalore",
            "351": "Mysore",
            "367": "Nanjangud",
            "417": "Puttur",
            "420": "Raichur",
            "467": "Shimoga",
            "475": "Sirsi",
            "526": "Tumkur",
            "531": "Udupi"
        },
        "Madhya Pradesh": {
            "36": "Balaghat",
            "75": "Bhopal",
            "109": "Chhatarpur",
            "110": "Chhindwara",
            "197": "Guna",
            "201": "Gwalior",
            "217": "Hoshangabad",
            "226": "Indore City",
            "227": "Indore Moffusil",
            "229": "Jabalpur",
            "275": "Khandwa",
            "322": "Mandsaur",
            "345": "Morena",
            "433": "Ratlam",
            "436": "Rewa",
            "444": "Sagar",
            "461": "Sehore",
            "464": "Shahdol",
            "532": "Ujjain",
            "546": "Vidisha"
        },
        "Assam": {
            "53": "Barpeta",
            "84": "Bongaigaon",
            "91": "Cachar",
            "131": "Darrang",
            "142": "Dhemaji",
            "145": "Dhubri",
            "148": "Dibrugarh",
            "187": "Goalpara",
            "189": "Golaghat",
            "202": "Hailakandi",
            "246": "Jorhat",
            "251": "Kamrup",
            "262": "Karbi Anglong",
            "264": "Karimganj",
            "281": "Kokrajhar",
            "299": "Lakhimpur",
            "327": "Marigaon",
            "353": "Nagaon",
            "359": "Nalbari",
            "377": "North Cachar Hills",
            "469": "Sibsagar",
            "484": "Sonitpur",
            "511": "Tinsukia"
        },
        "Chhattisgarh": {
            "54": "Bastar",
            "81": "Bilaspur",
            "155": "Durg",
            "421": "Raigarh (CT)",
            "423": "Raipur"
        },
        "Manipur": {
            "83": "Bishnupur",
            "99": "Chandel",
            "117": "Churachandpur",
            "224": "Imphal East",
            "225": "Imphal West",
            "462": "Senapati",
            "500": "Tamenglong",
            "510": "Thoubal",
            "533": "Ukhrul"
        },
        "Andaman and Nicobar Islands": {
            "93": "Carnicobar",
            "149": "Diglipur",
            "174": "Ferrargunj",
            "220": "Hut Bay",
            "331": "Mayabander",
            "362": "Nancorie",
            "363": "Nancowrie",
            "407": "Port Blair",
            "432": "Rangat"
        },
        "Himachal Pradesh": {
            "94": "Chamba",
            "133": "Dehra Gopipur",
            "139": "Dharamsala",
            "203": "Hamirpur (HP)",
            "321": "Mandi",
            "430": "Rampur Bushahr",
            "466": "Shimla",
            "480": "Solan",
            "534": "Una"
        },
        "Chandigarh": {
            "100": "Chandigarh"
        },
        "Arunachal Pradesh": {
            "103": "Changlang",
            "147": "Dibang Valley",
            "158": "East Kameng",
            "160": "East Siang",
            "296": "Kurung Kumey",
            "305": "Lohit",
            "307": "Lower Subansiri",
            "387": "Papum Pare",
            "503": "Tawang",
            "512": "Tirap",
            "536": "Upper Siang",
            "537": "Upper Subansiri",
            "558": "West Kameng",
            "560": "West Siang"
        },
        "Dadra and Nagar Haveli": {
            "127": "Dadra & Nagar Haveli"
        },
        "Daman and Diu": {
            "128": "Daman",
            "152": "Diu"
        },
        "Delhi": {
            "135": "Delhi"
        },
        "Tripura": {
            "137": "Dhalai",
            "380": "North Tripura",
            "489": "South Tripura",
            "562": "West Tripura"
        },
        "Jharkhand": {
            "138": "Dhanbad",
            "185": "Giridih",
            "212": "Hazaribagh",
            "383": "Palamau",
            "431": "Ranchi",
            "456": "Santhal Parganas",
            "473": "Singhbhum"
        },
        "Nagaland": {
            "150": "Dimapur",
            "278": "Kiphire",
            "280": "Kohima",
            "306": "Longleng",
            "341": "Mokokchung",
            "342": "Mon",
            "397": "Peren",
            "398": "Phek",
            "525": "Tuensang",
            "563": "Wokha",
            "565": "Zunhebotto"
        },
        "Meghalaya": {
            "157": "East Garo Hills",
            "159": "East Khasi Hills",
            "230": "Jaintia Hills",
            "336": "Meghalaya",
            "437": "Ri Bhoi",
            "487": "South Garo Hills",
            "557": "West Garo Hills",
            "559": "West Khasi Hills"
        },
        "Sikkim": {
            "161": "East Sikkim",
            "379": "North Sikkim",
            "488": "South Sikkim",
            "561": "West Sikkim"
        },
        "Goa": {
            "186": "Goa"
        },
        "Puducherry": {
            "259": "Karaikal",
            "402": "Poducherry (PD)"
        },
        "Lakshadweep": {
            "300": "Lakshadweep"
        }
    },
    "address": {
        "houseDetails": null,
        "street": null,
        "pinCode": null,
        "cityId": 0
    },
    "roleModules": {
        "1": "Admin",
        "2": "Distributor",
        "3": "Retailer",
        "4": "Agent",
        "5": "Support"
    },
    "selectedRole": null,
    "organizationTypes": {
        "1": "Owner",
        "2": "Distributer",
        "3": "Retailer"
    },
    "selectedOrganization": null,
    "commissionModel": 0,
    "creditEligible": false,
    "creditLimit": 0,
    "elegibleForIncentives": false,
    "bankNames": [
        "HDFC",
        "HDFC",
        "SBI",
        "SBI",
        "CITI",
        "CITI",
        "HSBC",
        "HSBC"
    ],
    "userBanks": []
}